// <auto-generated />
using EmergentEngineering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EmergentEngineering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704140000_AddLogRetentionSettings")]
    partial class AddLogRetentionSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
