// <auto-generated />
using EmergentEngineering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EmergentEngineering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707150000_AddLogDetailSettings")]
    partial class AddLogDetailSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
