// <auto-generated />
using System;
using EmergentEngineering.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmergentEngineering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714205551_AddThinkingSpeedModel")]
    partial class AddThinkingSpeedModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmergentEngineering.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("SimulationProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TrustJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SimulationProjectId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("EmergentEngineering.Models.AgentAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawLlmResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimulationProjectId")
                        .HasColumnType("int");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<string>("TargetAgentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double?>("TrustAfter")
                        .HasColumnType("float");

                    b.Property<double?>("TrustBefore")
                        .HasColumnType("float");

                    b.Property<double?>("TrustDelta")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("SimulationProjectId", "StepNo");

                    b.ToTable("AgentActions");
                });

            modelBuilder.Entity("EmergentEngineering.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentCount")
                        .HasColumnType("int");

                    b.Property<string>("BoundaryConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallengeDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<double>("ChallengeLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("ChallengeStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("None");

                    b.Property<double>("CompetitionLevel")
                        .HasColumnType("float");

                    b.Property<double>("ConstructiveCriticismBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.01);

                    b.Property<double>("CooperationLevel")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CrossDomainExposure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("CustomerOrientationLevel")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistrustPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.050000000000000003);

                    b.Property<double>("EffectiveTrustThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<bool>("EnableChallengeEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableExternalShock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableIntellectualRespect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableSerendipity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableThanksCoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableThinkingSpeedModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableTrustDynamics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("ExplorationTendency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ExternalShockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("InformationSharingLevel")
                        .HasColumnType("float");

                    b.Property<double>("IntellectualRespectBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("IntellectualRespectChallengeSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("IntellectualRespectDecayRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.002);

                    b.Property<double>("IntellectualRespectDiversitySensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("IntellectualRespectEgoPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("IntellectualRespectGrowthRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.040000000000000001);

                    b.Property<double>("IntellectualRespectHierarchyPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("IntellectualRespectMentorshipSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("KnowledgeDiversity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("KnowledgeRecombinationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("KnowledgeStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("KpiDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LearningOrientationLevel")
                        .HasColumnType("float");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("MutualRespectBase")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectBridgeSensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectChallengeSensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectDecayRate")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectDiversitySensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectGrowthRate")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectPopularityPenalty")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("OrganizationalDecisionSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("OrganizationalValidationSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("PsychologicalSafetyLevel")
                        .HasColumnType("float");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RequiredCrossDomainExposure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("RequiredKnowledgeDiversity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("RequiredRewiringScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("RewiringSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<int>("RunCount")
                        .HasColumnType("int");

                    b.Property<int?>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<double>("SerendipitySensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("SerendipityThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<string>("ShockDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("ShockStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ShockType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("None");

                    b.Property<double>("ShortTermResultPressureLevel")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("ThanksCoinBridgeGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinChallengeBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("ThanksCoinDiversityBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ThanksCoinPopularityBias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ThanksCoinPsychologicalSafetyGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.02);

                    b.Property<double>("ThanksCoinRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("ThanksCoinReconfigurationGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinRespectGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinTrustGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.01);

                    b.Property<double>("ThinkingSpeedBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("ThinkingSpeedDispersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<int>("TrustCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<double>("TrustCapacityPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("TrustDecayRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.002);

                    b.Property<double>("TrustGrowthRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("TrustSaturationStrength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.69999999999999996);

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("EmergentEngineering.Models.ExperimentRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageTrust")
                        .HasColumnType("float");

                    b.Property<int>("CompletedSteps")
                        .HasColumnType("int");

                    b.Property<int>("ComponentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CriticizeSupportRatio")
                        .HasColumnType("float");

                    b.Property<double>("EffectiveNetworkDensity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<string>("FinalPhase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HubAgentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("HubScore")
                        .HasColumnType("float");

                    b.Property<int>("IsolatedAgentCount")
                        .HasColumnType("int");

                    b.Property<double>("NetworkDensity")
                        .HasColumnType("float");

                    b.Property<int>("PhaseChangeCount")
                        .HasColumnType("int");

                    b.Property<double>("PhaseStability")
                        .HasColumnType("float");

                    b.Property<double>("ProposeIdeaRate")
                        .HasColumnType("float");

                    b.Property<int>("RunNo")
                        .HasColumnType("int");

                    b.Property<double>("ShareInfoRate")
                        .HasColumnType("float");

                    b.Property<int>("SimulationProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("StepsToEmergent")
                        .HasColumnType("int");

                    b.Property<int?>("StepsToLearning")
                        .HasColumnType("int");

                    b.Property<int>("StrongLinkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WeakLinkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SimulationProjectId");

                    b.HasIndex("ExperimentId", "RunNo")
                        .IsUnique();

                    b.ToTable("ExperimentRuns");
                });

            modelBuilder.Entity("EmergentEngineering.Models.ParameterSweep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EndValue")
                        .HasColumnType("float");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RunCountPerValue")
                        .HasColumnType("int");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<double>("StartValue")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("StepValue")
                        .HasColumnType("float");

                    b.Property<string>("TargetParameter")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ParameterSweeps");
                });

            modelBuilder.Entity("EmergentEngineering.Models.ParameterSweepRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageAbsTrust")
                        .HasColumnType("float");

                    b.Property<double>("AverageTrust")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<string>("FinalPhaseSummaryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParameterSweepId")
                        .HasColumnType("int");

                    b.Property<double>("ParameterValue")
                        .HasColumnType("float");

                    b.Property<int>("RunCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParameterSweepId", "ParameterValue");

                    b.ToTable("ParameterSweepRuns");
                });

            modelBuilder.Entity("EmergentEngineering.Models.PhaseDiagram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdaptiveReason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("AdaptiveSourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<int>("AgentCount")
                        .HasColumnType("int");

                    b.Property<int>("BaseScenarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdaptiveSweep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasDefaultValue("mock-v1");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Mock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentPhaseDiagramId")
                        .HasColumnType("int");

                    b.Property<int>("RunsPerPoint")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Created");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<double>("XEndValue")
                        .HasColumnType("float");

                    b.Property<string>("XParameterDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("XParameterName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("XStartValue")
                        .HasColumnType("float");

                    b.Property<double>("XStepValue")
                        .HasColumnType("float");

                    b.Property<double>("YEndValue")
                        .HasColumnType("float");

                    b.Property<string>("YParameterDisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("YParameterName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("YStartValue")
                        .HasColumnType("float");

                    b.Property<double>("YStepValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BaseScenarioId");

                    b.HasIndex("ParentPhaseDiagramId");

                    b.ToTable("PhaseDiagrams");
                });

            modelBuilder.Entity("EmergentEngineering.Models.PhaseDiagramPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageEffectiveDensity")
                        .HasColumnType("float");

                    b.Property<double>("AverageKnowledgeDiversity")
                        .HasColumnType("float");

                    b.Property<double>("AverageKnowledgeRecombinationScore")
                        .HasColumnType("float");

                    b.Property<double>("AverageKnowledgeReconfigurationScore")
                        .HasColumnType("float");

                    b.Property<double>("AveragePipelineCompletionScore")
                        .HasColumnType("float");

                    b.Property<double>("AverageSerendipityRate")
                        .HasColumnType("float");

                    b.Property<double>("AverageTrust")
                        .HasColumnType("float");

                    b.Property<double>("ChaosRate")
                        .HasColumnType("float");

                    b.Property<double>("CollapseRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DominantBottleneck")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DominantPhase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("EmergentRate")
                        .HasColumnType("float");

                    b.Property<int?>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<string>("FinalPhaseSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LearningRate")
                        .HasColumnType("float");

                    b.Property<int>("PhaseDiagramId")
                        .HasColumnType("int");

                    b.Property<double>("SiloRate")
                        .HasColumnType("float");

                    b.Property<double>("StableRate")
                        .HasColumnType("float");

                    b.Property<double>("XValue")
                        .HasColumnType("float");

                    b.Property<double>("YValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("PhaseDiagramId", "XValue", "YValue")
                        .IsUnique();

                    b.ToTable("PhaseDiagramPoints");
                });

            modelBuilder.Entity("EmergentEngineering.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentCount")
                        .HasColumnType("int");

                    b.Property<string>("BoundaryConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallengeDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<double>("ChallengeLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("ChallengeStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("None");

                    b.Property<double>("CompetitionLevel")
                        .HasColumnType("float");

                    b.Property<double>("ConstructiveCriticismBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.01);

                    b.Property<double>("CooperationLevel")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CrossDomainExposure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("CustomerOrientationLevel")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistrustPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.050000000000000003);

                    b.Property<double>("EffectiveTrustThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<bool>("EnableChallengeEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableExternalShock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableIntellectualRespect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableSerendipity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableThanksCoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableThinkingSpeedModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableTrustDynamics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double>("ExplorationTendency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ExternalShockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("InformationSharingLevel")
                        .HasColumnType("float");

                    b.Property<double>("IntellectualRespectBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("IntellectualRespectChallengeSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("IntellectualRespectDecayRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.002);

                    b.Property<double>("IntellectualRespectDiversitySensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("IntellectualRespectEgoPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("IntellectualRespectGrowthRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.040000000000000001);

                    b.Property<double>("IntellectualRespectHierarchyPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("IntellectualRespectMentorshipSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("KnowledgeDiversity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("KnowledgeRecombinationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("KnowledgeStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("KpiDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LearningOrientationLevel")
                        .HasColumnType("float");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("MutualRespectBase")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectBridgeSensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectChallengeSensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectDecayRate")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectDiversitySensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectGrowthRate")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectPopularityPenalty")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("OrganizationalDecisionSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("OrganizationalValidationSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("PsychologicalSafetyLevel")
                        .HasColumnType("float");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RequiredCrossDomainExposure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("RequiredKnowledgeDiversity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("RequiredRewiringScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("RewiringSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<int>("RunCount")
                        .HasColumnType("int");

                    b.Property<double>("SerendipitySensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("SerendipityThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<string>("ShockDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("ShockStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ShockType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("None");

                    b.Property<double>("ShortTermResultPressureLevel")
                        .HasColumnType("float");

                    b.Property<double>("ThanksCoinBridgeGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinChallengeBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("ThanksCoinDiversityBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ThanksCoinPopularityBias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ThanksCoinPsychologicalSafetyGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.02);

                    b.Property<double>("ThanksCoinRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("ThanksCoinReconfigurationGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinRespectGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinTrustGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.01);

                    b.Property<double>("ThinkingSpeedBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("ThinkingSpeedDispersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<int>("TrustCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<double>("TrustCapacityPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("TrustDecayRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.002);

                    b.Property<double>("TrustGrowthRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("TrustSaturationStrength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.69999999999999996);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("EmergentEngineering.Models.SimulationMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageTrust")
                        .HasColumnType("float");

                    b.Property<int>("ComponentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CriticizeSupportRatio")
                        .HasColumnType("float");

                    b.Property<double>("EffectiveNetworkDensity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("FinalPhase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HubAgentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("HubScore")
                        .HasColumnType("float");

                    b.Property<int>("IsolatedAgentCount")
                        .HasColumnType("int");

                    b.Property<double>("NetworkDensity")
                        .HasColumnType("float");

                    b.Property<int>("PhaseChangeCount")
                        .HasColumnType("int");

                    b.Property<double>("PhaseStability")
                        .HasColumnType("float");

                    b.Property<double>("ProposeIdeaRate")
                        .HasColumnType("float");

                    b.Property<double>("ShareInfoRate")
                        .HasColumnType("float");

                    b.Property<int>("SimulationProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("StepsToEmergent")
                        .HasColumnType("int");

                    b.Property<int?>("StepsToLearning")
                        .HasColumnType("int");

                    b.Property<int>("StrongLinkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WeakLinkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("SimulationProjectId")
                        .IsUnique();

                    b.ToTable("SimulationMetrics");
                });

            modelBuilder.Entity("EmergentEngineering.Models.SimulationProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentCount")
                        .HasColumnType("int");

                    b.Property<string>("BoundaryConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallengeDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<double>("ChallengeLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("ChallengeStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("None");

                    b.Property<double>("CompetitionLevel")
                        .HasColumnType("float");

                    b.Property<double>("ConstructiveCriticismBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.01);

                    b.Property<double>("CooperationLevel")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CrossDomainExposure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<double>("CustomerOrientationLevel")
                        .HasColumnType("float");

                    b.Property<double>("DistrustPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.050000000000000003);

                    b.Property<double>("EffectiveTrustThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<bool>("EnableChallengeEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableExternalShock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableIntellectualRespect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableSerendipity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableThanksCoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableThinkingSpeedModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableTrustDynamics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<int?>("ExperimentRunId")
                        .HasColumnType("int");

                    b.Property<double>("ExplorationTendency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ExternalShockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("InformationSharingLevel")
                        .HasColumnType("float");

                    b.Property<double>("IntellectualRespectBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("IntellectualRespectChallengeSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("IntellectualRespectDecayRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.002);

                    b.Property<double>("IntellectualRespectDiversitySensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("IntellectualRespectEgoPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("IntellectualRespectGrowthRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.040000000000000001);

                    b.Property<double>("IntellectualRespectHierarchyPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("IntellectualRespectMentorshipSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("KnowledgeDiversity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("KnowledgeRecombinationRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("KnowledgeStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("KpiDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LearningOrientationLevel")
                        .HasColumnType("float");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("MutualRespectBase")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectBridgeSensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectChallengeSensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectDecayRate")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectDiversitySensitivity")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectGrowthRate")
                        .HasColumnType("float");

                    b.Property<double>("MutualRespectPopularityPenalty")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("OrganizationalDecisionSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("OrganizationalValidationSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("PsychologicalSafetyLevel")
                        .HasColumnType("float");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RequiredCrossDomainExposure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("RequiredKnowledgeDiversity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("RequiredRewiringScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("RewiringSensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<double>("SerendipitySensitivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("SerendipityThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.5);

                    b.Property<string>("ShockDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("ShockStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ShockType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("None");

                    b.Property<double>("ShortTermResultPressureLevel")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("ThanksCoinBridgeGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinChallengeBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("ThanksCoinDiversityBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ThanksCoinPopularityBias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.29999999999999999);

                    b.Property<double>("ThanksCoinPsychologicalSafetyGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.02);

                    b.Property<double>("ThanksCoinRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.20000000000000001);

                    b.Property<double>("ThanksCoinReconfigurationGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinRespectGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("ThanksCoinTrustGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.01);

                    b.Property<double>("ThinkingSpeedBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("ThinkingSpeedDispersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<int>("TrustCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<double>("TrustCapacityPenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.029999999999999999);

                    b.Property<double>("TrustDecayRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.002);

                    b.Property<double>("TrustGrowthRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<double>("TrustSaturationStrength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.69999999999999996);

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.ToTable("SimulationProjects");
                });

            modelBuilder.Entity("EmergentEngineering.Models.SimulationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SimulationProjectId")
                        .HasColumnType("int");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SimulationProjectId", "StepNo")
                        .IsUnique();

                    b.ToTable("SimulationSteps");
                });

            modelBuilder.Entity("EmergentEngineering.Models.TrustSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SimulationProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SourceAgentId")
                        .HasColumnType("int");

                    b.Property<string>("SourceAgentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<int>("TargetAgentId")
                        .HasColumnType("int");

                    b.Property<string>("TargetAgentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<double>("TrustValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SimulationProjectId", "StepNo");

                    b.HasIndex("SimulationProjectId", "StepNo", "SourceAgentId", "TargetAgentId")
                        .IsUnique();

                    b.ToTable("TrustSnapshots");
                });

            modelBuilder.Entity("EmergentEngineering.Models.Agent", b =>
                {
                    b.HasOne("EmergentEngineering.Models.SimulationProject", "SimulationProject")
                        .WithMany("Agents")
                        .HasForeignKey("SimulationProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationProject");
                });

            modelBuilder.Entity("EmergentEngineering.Models.AgentAction", b =>
                {
                    b.HasOne("EmergentEngineering.Models.Agent", "Agent")
                        .WithMany("Actions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("EmergentEngineering.Models.Experiment", b =>
                {
                    b.HasOne("EmergentEngineering.Models.Scenario", "Scenario")
                        .WithMany("Experiments")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("EmergentEngineering.Models.ExperimentRun", b =>
                {
                    b.HasOne("EmergentEngineering.Models.Experiment", "Experiment")
                        .WithMany("Runs")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmergentEngineering.Models.SimulationProject", "SimulationProject")
                        .WithMany()
                        .HasForeignKey("SimulationProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("SimulationProject");
                });

            modelBuilder.Entity("EmergentEngineering.Models.ParameterSweepRun", b =>
                {
                    b.HasOne("EmergentEngineering.Models.ParameterSweep", "ParameterSweep")
                        .WithMany("Runs")
                        .HasForeignKey("ParameterSweepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParameterSweep");
                });

            modelBuilder.Entity("EmergentEngineering.Models.PhaseDiagram", b =>
                {
                    b.HasOne("EmergentEngineering.Models.Scenario", "BaseScenario")
                        .WithMany()
                        .HasForeignKey("BaseScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmergentEngineering.Models.PhaseDiagram", "ParentPhaseDiagram")
                        .WithMany()
                        .HasForeignKey("ParentPhaseDiagramId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BaseScenario");

                    b.Navigation("ParentPhaseDiagram");
                });

            modelBuilder.Entity("EmergentEngineering.Models.PhaseDiagramPoint", b =>
                {
                    b.HasOne("EmergentEngineering.Models.Experiment", "Experiment")
                        .WithMany()
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EmergentEngineering.Models.PhaseDiagram", "PhaseDiagram")
                        .WithMany("Points")
                        .HasForeignKey("PhaseDiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("PhaseDiagram");
                });

            modelBuilder.Entity("EmergentEngineering.Models.SimulationMetrics", b =>
                {
                    b.HasOne("EmergentEngineering.Models.SimulationProject", "SimulationProject")
                        .WithOne("Metrics")
                        .HasForeignKey("EmergentEngineering.Models.SimulationMetrics", "SimulationProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationProject");
                });

            modelBuilder.Entity("EmergentEngineering.Models.SimulationProject", b =>
                {
                    b.HasOne("EmergentEngineering.Models.Experiment", "Experiment")
                        .WithMany("SimulationProjects")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("EmergentEngineering.Models.SimulationStep", b =>
                {
                    b.HasOne("EmergentEngineering.Models.SimulationProject", "SimulationProject")
                        .WithMany("Steps")
                        .HasForeignKey("SimulationProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationProject");
                });

            modelBuilder.Entity("EmergentEngineering.Models.TrustSnapshot", b =>
                {
                    b.HasOne("EmergentEngineering.Models.SimulationProject", "SimulationProject")
                        .WithMany("TrustSnapshots")
                        .HasForeignKey("SimulationProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationProject");
                });

            modelBuilder.Entity("EmergentEngineering.Models.Agent", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("EmergentEngineering.Models.Experiment", b =>
                {
                    b.Navigation("Runs");

                    b.Navigation("SimulationProjects");
                });

            modelBuilder.Entity("EmergentEngineering.Models.ParameterSweep", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("EmergentEngineering.Models.PhaseDiagram", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("EmergentEngineering.Models.Scenario", b =>
                {
                    b.Navigation("Experiments");
                });

            modelBuilder.Entity("EmergentEngineering.Models.SimulationProject", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Metrics");

                    b.Navigation("Steps");

                    b.Navigation("TrustSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
